export const EXPORT_FORMATS = ['csv', 'xlsx', 'pdf'];

export const EXPORT_MIME = {
  csv: 'text/csv; charset=utf-8',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  pdf: 'application/pdf',
};

export const EXPORT_EXTENSIONS = {
  csv: 'csv',
  xlsx: 'xlsx',
  pdf: 'pdf',
};

export const REPORT_EXPORT_COLUMNS = {
  fleet: [
    { key: 'registrationNumber', label: 'Immatriculation' },
    { key: 'vehicle', label: 'Véhicule' },
    { key: 'group', label: 'Groupe' },
    { key: 'status', label: 'Statut' },
    { key: 'mileage', label: 'Kilométrage' },
    { key: 'fuelType', label: 'Carburant' },
    { key: 'createdAt', label: 'Date création' },
  ],
  vehicles: [
    { key: 'registrationNumber', label: 'Immatriculation' },
    { key: 'vehicle', label: 'Véhicule' },
    { key: 'group', label: 'Groupe' },
    { key: 'status', label: 'Statut' },
    { key: 'mileage', label: 'Kilométrage' },
    { key: 'fuelType', label: 'Carburant' },
    { key: 'tripCount', label: 'Trajets' },
    { key: 'totalDistance', label: 'Distance (km)' },
    { key: 'fuelCost', label: 'Coût carburant (XAF)' },
    { key: 'maintenanceCost', label: 'Coût entretien (XAF)' },
  ],
  drivers: [
    { key: 'fullName', label: 'Nom complet' },
    { key: 'employeeCode', label: 'Code employé' },
    { key: 'status', label: 'Statut' },
    { key: 'licenseNumber', label: 'N° permis' },
    { key: 'licenseExpiry', label: 'Expiration permis' },
    { key: 'tripCount', label: 'Trajets' },
    { key: 'totalDistance', label: 'Distance (km)' },
    { key: 'totalDuration', label: 'Durée totale' },
    { key: 'fuelCost', label: 'Coût carburant (XAF)' },
  ],
  assignments: [
    { key: 'assignmentNumber', label: 'N° affectation' },
    { key: 'vehicle', label: 'Véhicule' },
    { key: 'driver', label: 'Chauffeur' },
    { key: 'type', label: 'Type' },
    { key: 'status', label: 'Statut' },
    { key: 'startDate', label: 'Date début' },
    { key: 'endDate', label: 'Date fin' },
    { key: 'destination', label: 'Destination' },
  ],
  trips: [
    { key: 'tripNumber', label: 'N° trajet' },
    { key: 'vehicle', label: 'Véhicule' },
    { key: 'driver', label: 'Chauffeur' },
    { key: 'type', label: 'Type' },
    { key: 'status', label: 'Statut' },
    { key: 'origin', label: 'Origine' },
    { key: 'destination', label: 'Destination' },
    { key: 'distance', label: 'Distance (km)' },
    { key: 'duration', label: 'Durée' },
    { key: 'purpose', label: 'Motif' },
  ],
  fuel: [
    { key: 'fuelNumber', label: 'N° plein' },
    { key: 'vehicle', label: 'Véhicule' },
    { key: 'driver', label: 'Chauffeur' },
    { key: 'type', label: 'Type' },
    { key: 'quantity', label: 'Quantité (L)' },
    { key: 'unitPrice', label: 'Prix unitaire' },
    { key: 'totalAmount', label: 'Montant total (XAF)' },
    { key: 'mileage', label: 'Kilométrage' },
    { key: 'station', label: 'Station' },
    { key: 'date', label: 'Date' },
  ],
  maintenance: [
    { key: 'number', label: 'N° entretien' },
    { key: 'vehicle', label: 'Véhicule' },
    { key: 'type', label: 'Type' },
    { key: 'priority', label: 'Priorité' },
    { key: 'status', label: 'Statut' },
    { key: 'scheduledDate', label: 'Date prévue' },
    { key: 'completedDate', label: 'Date fin' },
    { key: 'estimatedCost', label: 'Coût estimé (XAF)' },
    { key: 'actualCost', label: 'Coût réel (XAF)' },
    { key: 'workshop', label: 'Atelier' },
  ],
  documents: [
    { key: 'name', label: 'Nom' },
    { key: 'category', label: 'Catégorie' },
    { key: 'extension', label: 'Type' },
    { key: 'size', label: 'Taille' },
    { key: 'visibility', label: 'Visibilité' },
    { key: 'uploadedBy', label: 'Uploadé par' },
    { key: 'createdAt', label: 'Date création' },
  ],
  financial: [
    { key: 'reference', label: 'Référence' },
    { key: 'type', label: 'Type' },
    { key: 'status', label: 'Statut' },
    { key: 'totalAmount', label: 'Montant (XAF)' },
    { key: 'paidAmount', label: 'Payé (XAF)' },
    { key: 'outstanding', label: 'Restant (XAF)' },
    { key: 'dueDate', label: 'Échéance' },
    { key: 'client', label: 'Client' },
  ],
  subscriptions: [
    { key: 'company', label: 'Entreprise' },
    { key: 'plan', label: 'Plan' },
    { key: 'status', label: 'Statut' },
    { key: 'price', label: 'Prix (XAF)' },
    { key: 'billingInterval', label: 'Intervalle' },
    { key: 'startDate', label: 'Date début' },
    { key: 'endDate', label: 'Date fin' },
  ],
  audit: [
    { key: 'action', label: 'Action' },
    { key: 'actionType', label: 'Type action' },
    { key: 'resourceType', label: 'Ressource' },
    { key: 'resourceId', label: 'ID ressource' },
    { key: 'description', label: 'Description' },
    { key: 'status', label: 'Statut' },
    { key: 'severity', label: 'Sévérité' },
    { key: 'userName', label: 'Utilisateur' },
    { key: 'createdAt', label: 'Date' },
  ],
  companies: [
    { key: 'name', label: 'Nom' },
    { key: 'code', label: 'Code' },
    { key: 'status', label: 'Statut' },
    { key: 'vehicleCount', label: 'Véhicules' },
    { key: 'driverCount', label: 'Chauffeurs' },
    { key: 'createdAt', label: 'Date création' },
  ],
};

export const REPORT_TYPE_LABELS = {
  fleet: 'Parc automobile',
  vehicles: 'Véhicules',
  drivers: 'Chauffeurs',
  assignments: 'Affectations',
  trips: 'Trajets',
  fuel: 'Carburant',
  maintenance: 'Entretiens',
  documents: 'Documents',
  financial: 'Finances',
  subscriptions: 'Abonnements',
  audit: 'Journal des actions',
  companies: 'Entreprises',
};

export const MAX_EXPORT_ROWS = 50000;
