CREATE TABLE IF NOT EXISTS companies (
  id CHAR(26) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  legal_name VARCHAR(255),
  slug VARCHAR(255) NOT NULL UNIQUE,
  registration_number VARCHAR(100),
  tax_number VARCHAR(100),
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  city VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Cameroun',
  logo_url VARCHAR(500),
  status ENUM('active','inactive','suspended') NOT NULL DEFAULT 'active',
  subscription_plan VARCHAR(50) DEFAULT 'starter',
  subscription_status VARCHAR(50) DEFAULT 'active',
  max_users INT DEFAULT 5,
  max_vehicles INT DEFAULT 10,
  is_active BOOLEAN DEFAULT TRUE,
  settings JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_companies_slug (slug),
  INDEX idx_companies_status (status),
  INDEX idx_companies_is_active (is_active),
  INDEX idx_companies_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
