CREATE TABLE IF NOT EXISTS users (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26),
  email VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'client_enterprise',
  phone VARCHAR(50),
  avatar_url VARCHAR(500),
  status ENUM('active','inactive','suspended','pending') NOT NULL DEFAULT 'active',
  email_verified_at TIMESTAMP NULL DEFAULT NULL,
  last_login_at TIMESTAMP NULL DEFAULT NULL,
  refresh_token_hash VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_users_email (email),
  INDEX idx_users_company_id (company_id),
  INDEX idx_users_role (role),
  INDEX idx_users_status (status),
  INDEX idx_users_deleted_at (deleted_at),
  CONSTRAINT fk_users_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
