CREATE TABLE IF NOT EXISTS vehicles (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  agency_id CHAR(26),
  vehicle_type_id CHAR(26),
  registration_number VARCHAR(50) NOT NULL,
  vin VARCHAR(50),
  engine_number VARCHAR(100),
  brand VARCHAR(100) NOT NULL,
  model VARCHAR(100) NOT NULL,
  version VARCHAR(100),
  year INT,
  color VARCHAR(50),
  fuel_type ENUM('diesel','essence','hybride','electrique') NOT NULL DEFAULT 'diesel',
  transmission ENUM('manuelle','automatique') NOT NULL DEFAULT 'manuelle',
  capacity INT DEFAULT 5,
  mileage INT DEFAULT 0,
  group_code VARCHAR(10),
  category VARCHAR(100),
  status ENUM('available','in_use','maintenance','out_of_service') NOT NULL DEFAULT 'available',
  purchase_date DATE,
  purchase_price DECIMAL(15, 2),
  insurance_expiry DATE,
  inspection_expiry DATE,
  registration_expiry DATE,
  photo_url VARCHAR(500),
  qr_code VARCHAR(100),
  notes TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_vehicles_registration_company (company_id, registration_number),
  INDEX idx_vehicles_company_id (company_id),
  INDEX idx_vehicles_agency_id (agency_id),
  INDEX idx_vehicles_vehicle_type_id (vehicle_type_id),
  INDEX idx_vehicles_status (status),
  INDEX idx_vehicles_fuel_type (fuel_type),
  INDEX idx_vehicles_group_code (group_code),
  INDEX idx_vehicles_vin (vin),
  INDEX idx_vehicles_created_at (created_at),
  INDEX idx_vehicles_deleted_at (deleted_at),
  CONSTRAINT fk_vehicles_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_vehicles_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL,
  CONSTRAINT fk_vehicles_type FOREIGN KEY (vehicle_type_id) REFERENCES vehicle_types(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
