CREATE TABLE IF NOT EXISTS drivers (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  agency_id CHAR(26),
  user_id CHAR(26),
  employee_code VARCHAR(50),
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  gender ENUM('male','female','other'),
  birth_date DATE,
  phone VARCHAR(50),
  email VARCHAR(255),
  address TEXT,
  city VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Cameroun',
  nationality VARCHAR(100),
  license_number VARCHAR(100),
  license_category VARCHAR(10),
  license_issue_date DATE,
  license_expiry_date DATE,
  years_experience INT DEFAULT 0,
  status ENUM('active','on_mission','available','suspended','on_leave','inactive') NOT NULL DEFAULT 'active',
  availability ENUM('available','busy','unavailable') NOT NULL DEFAULT 'available',
  photo_url VARCHAR(500),
  identity_document VARCHAR(255),
  emergency_contact_name VARCHAR(255),
  emergency_contact_phone VARCHAR(50),
  notes TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_drivers_employee_code_company (company_id, employee_code),
  INDEX idx_drivers_company_id (company_id),
  INDEX idx_drivers_agency_id (agency_id),
  INDEX idx_drivers_user_id (user_id),
  INDEX idx_drivers_status (status),
  INDEX idx_drivers_availability (availability),
  INDEX idx_drivers_license_expiry (license_expiry_date),
  INDEX idx_drivers_deleted_at (deleted_at),
  CONSTRAINT fk_drivers_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_drivers_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL,
  CONSTRAINT fk_drivers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
