CREATE TABLE IF NOT EXISTS clients (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  user_id CHAR(26),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  city VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Cameroun',
  contact_person VARCHAR(255),
  tax_number VARCHAR(100),
  status ENUM('active','inactive','suspended') NOT NULL DEFAULT 'active',
  is_active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_clients_company_id (company_id),
  INDEX idx_clients_user_id (user_id),
  INDEX idx_clients_status (status),
  INDEX idx_clients_deleted_at (deleted_at),
  CONSTRAINT fk_clients_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_clients_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
