CREATE TABLE IF NOT EXISTS partners (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  user_id CHAR(26),
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  city VARCHAR(100),
  country VARCHAR(100) DEFAULT 'Cameroun',
  contact_person VARCHAR(255),
  partner_type VARCHAR(100),
  tax_number VARCHAR(100),
  status ENUM('active','inactive','suspended','pending') NOT NULL DEFAULT 'active',
  is_active BOOLEAN DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_partners_company_id (company_id),
  INDEX idx_partners_user_id (user_id),
  INDEX idx_partners_status (status),
  INDEX idx_partners_deleted_at (deleted_at),
  CONSTRAINT fk_partners_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_partners_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
