CREATE TABLE IF NOT EXISTS requests (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  client_id CHAR(26),
  partner_id CHAR(26),
  vehicle_id CHAR(26),
  request_number VARCHAR(50) NOT NULL,
  request_type VARCHAR(100) NOT NULL,
  subject VARCHAR(255),
  description TEXT,
  priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  status ENUM('pending','approved','in_progress','completed','cancelled','rejected') NOT NULL DEFAULT 'pending',
  requested_at TIMESTAMP NULL DEFAULT NULL,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_requests_number_company (company_id, request_number),
  INDEX idx_requests_company_id (company_id),
  INDEX idx_requests_client_id (client_id),
  INDEX idx_requests_partner_id (partner_id),
  INDEX idx_requests_status (status),
  INDEX idx_requests_created_at (created_at),
  INDEX idx_requests_deleted_at (deleted_at),
  CONSTRAINT fk_requests_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_requests_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_requests_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
  CONSTRAINT fk_requests_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
