CREATE TABLE IF NOT EXISTS missions (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  request_id CHAR(26),
  client_id CHAR(26),
  partner_id CHAR(26),
  vehicle_id CHAR(26),
  driver_id CHAR(26),
  mission_number VARCHAR(50) NOT NULL,
  mission_type VARCHAR(100),
  subject VARCHAR(255),
  description TEXT,
  origin VARCHAR(255),
  destination VARCHAR(255),
  start_at TIMESTAMP NULL DEFAULT NULL,
  end_at TIMESTAMP NULL DEFAULT NULL,
  status ENUM('planned','in_progress','completed','cancelled','suspended') NOT NULL DEFAULT 'planned',
  priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_missions_number_company (company_id, mission_number),
  INDEX idx_missions_company_id (company_id),
  INDEX idx_missions_request_id (request_id),
  INDEX idx_missions_client_id (client_id),
  INDEX idx_missions_vehicle_id (vehicle_id),
  INDEX idx_missions_driver_id (driver_id),
  INDEX idx_missions_status (status),
  INDEX idx_missions_start_at (start_at),
  INDEX idx_missions_created_at (created_at),
  INDEX idx_missions_deleted_at (deleted_at),
  CONSTRAINT fk_missions_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_missions_request FOREIGN KEY (request_id) REFERENCES requests(id) ON DELETE SET NULL,
  CONSTRAINT fk_missions_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_missions_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL,
  CONSTRAINT fk_missions_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE SET NULL,
  CONSTRAINT fk_missions_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
