CREATE TABLE IF NOT EXISTS assignments (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  agency_id CHAR(26),
  vehicle_id CHAR(26) NOT NULL,
  driver_id CHAR(26) NOT NULL,
  mission_id CHAR(26),
  assignment_number VARCHAR(50) NOT NULL,
  assignment_type ENUM('permanent','temporary','mission','replacement','maintenance','trial') NOT NULL DEFAULT 'temporary',
  status ENUM('planned','active','completed','cancelled','suspended') NOT NULL DEFAULT 'planned',
  start_date DATE NOT NULL,
  end_date DATE,
  expected_end_date DATE,
  start_mileage INT DEFAULT 0,
  end_mileage INT DEFAULT 0,
  fuel_level_start INT DEFAULT 0,
  fuel_level_end INT DEFAULT 0,
  reason TEXT,
  destination VARCHAR(255),
  created_by VARCHAR(255),
  validated_by VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_assignments_number_company (company_id, assignment_number),
  INDEX idx_assignments_company_id (company_id),
  INDEX idx_assignments_agency_id (agency_id),
  INDEX idx_assignments_vehicle_id (vehicle_id),
  INDEX idx_assignments_driver_id (driver_id),
  INDEX idx_assignments_mission_id (mission_id),
  INDEX idx_assignments_status (status),
  INDEX idx_assignments_start_date (start_date),
  INDEX idx_assignments_end_date (end_date),
  INDEX idx_assignments_vehicle_status (vehicle_id, status),
  INDEX idx_assignments_driver_status (driver_id, status),
  INDEX idx_assignments_created_at (created_at),
  INDEX idx_assignments_deleted_at (deleted_at),
  CONSTRAINT fk_assignments_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_assignments_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL,
  CONSTRAINT fk_assignments_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
  CONSTRAINT fk_assignments_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
  CONSTRAINT fk_assignments_mission FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
