CREATE TABLE IF NOT EXISTS trips (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  mission_id CHAR(26),
  vehicle_id CHAR(26) NOT NULL,
  driver_id CHAR(26) NOT NULL,
  trip_number VARCHAR(50) NOT NULL,
  trip_type ENUM('mission','delivery','transport','service','maintenance','personnel','trial') NOT NULL DEFAULT 'mission',
  status ENUM('planned','in_progress','completed','cancelled','suspended') NOT NULL DEFAULT 'planned',
  origin VARCHAR(255),
  destination VARCHAR(255),
  departure_date DATE,
  departure_time TIME,
  arrival_date DATE,
  arrival_time TIME,
  distance DECIMAL(10, 2),
  duration_minutes INT,
  start_mileage INT,
  end_mileage INT,
  fuel_consumed DECIMAL(8, 2),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_trips_number_company (company_id, trip_number),
  INDEX idx_trips_company_id (company_id),
  INDEX idx_trips_mission_id (mission_id),
  INDEX idx_trips_vehicle_id (vehicle_id),
  INDEX idx_trips_driver_id (driver_id),
  INDEX idx_trips_status (status),
  INDEX idx_trips_trip_type (trip_type),
  INDEX idx_trips_departure_date (departure_date),
  INDEX idx_trips_created_at (created_at),
  INDEX idx_trips_deleted_at (deleted_at),
  CONSTRAINT fk_trips_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_trips_mission FOREIGN KEY (mission_id) REFERENCES missions(id) ON DELETE SET NULL,
  CONSTRAINT fk_trips_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
  CONSTRAINT fk_trips_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
