CREATE TABLE IF NOT EXISTS maintenance_records (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  vehicle_id CHAR(26) NOT NULL,
  maintenance_number VARCHAR(50) NOT NULL,
  maintenance_type ENUM('vidange','revision','controle_technique','freinage','pneumatiques','batterie','moteur','transmission','suspension','climatisation','carrosserie','reparation','inspection','autre') NOT NULL,
  priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
  status ENUM('planned','pending','in_progress','completed','cancelled') NOT NULL DEFAULT 'planned',
  description TEXT,
  provider VARCHAR(255),
  scheduled_date DATE,
  started_at TIMESTAMP NULL DEFAULT NULL,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  actual_cost DECIMAL(15, 2),
  estimated_cost DECIMAL(15, 2),
  mileage_at_service INT,
  next_maintenance_mileage INT,
  next_maintenance_date DATE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_maintenance_number_company (company_id, maintenance_number),
  INDEX idx_maintenance_company_id (company_id),
  INDEX idx_maintenance_vehicle_id (vehicle_id),
  INDEX idx_maintenance_status (status),
  INDEX idx_maintenance_type (maintenance_type),
  INDEX idx_maintenance_priority (priority),
  INDEX idx_maintenance_scheduled_date (scheduled_date),
  INDEX idx_maintenance_created_at (created_at),
  INDEX idx_maintenance_deleted_at (deleted_at),
  CONSTRAINT fk_maintenance_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_maintenance_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
