CREATE TABLE IF NOT EXISTS fuel_records (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  vehicle_id CHAR(26) NOT NULL,
  driver_id CHAR(26),
  fuel_number VARCHAR(50) NOT NULL,
  fuel_type ENUM('diesel','essence','hybride','electrique') NOT NULL DEFAULT 'diesel',
  quantity DECIMAL(10, 2) NOT NULL,
  unit_price DECIMAL(10, 2) NOT NULL,
  total_amount DECIMAL(15, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  mileage INT,
  station VARCHAR(255),
  filled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_fuel_number_company (company_id, fuel_number),
  INDEX idx_fuel_company_id (company_id),
  INDEX idx_fuel_vehicle_id (vehicle_id),
  INDEX idx_fuel_driver_id (driver_id),
  INDEX idx_fuel_type (fuel_type),
  INDEX idx_fuel_filled_at (filled_at),
  INDEX idx_fuel_created_at (created_at),
  INDEX idx_fuel_deleted_at (deleted_at),
  CONSTRAINT fk_fuel_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_fuel_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE CASCADE,
  CONSTRAINT fk_fuel_driver FOREIGN KEY (driver_id) REFERENCES drivers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
