CREATE TABLE IF NOT EXISTS documents (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  entity_type ENUM('company','vehicle','driver','client','partner','mission','assignment','trip','maintenance','fuel','contract','invoice','subscription','user') NOT NULL,
  entity_id CHAR(26) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  file_size BIGINT NOT NULL DEFAULT 0,
  mime_type VARCHAR(100) NOT NULL,
  file_extension VARCHAR(20) NOT NULL,
  category VARCHAR(100),
  visibility ENUM('public','private','restricted') NOT NULL DEFAULT 'private',
  description TEXT,
  uploaded_by CHAR(26),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  INDEX idx_documents_company_id (company_id),
  INDEX idx_documents_entity (entity_type, entity_id),
  INDEX idx_documents_category (category),
  INDEX idx_documents_mime_type (mime_type),
  INDEX idx_documents_created_at (created_at),
  INDEX idx_documents_deleted_at (deleted_at),
  CONSTRAINT fk_documents_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_documents_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
