CREATE TABLE IF NOT EXISTS contracts (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  client_id CHAR(26),
  partner_id CHAR(26),
  reference VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  contract_type VARCHAR(100),
  status ENUM('draft','active','suspended','completed','cancelled','expired') NOT NULL DEFAULT 'draft',
  start_date DATE NOT NULL,
  end_date DATE,
  value DECIMAL(15, 2),
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  payment_terms VARCHAR(255),
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_contracts_reference_company (company_id, reference),
  INDEX idx_contracts_company_id (company_id),
  INDEX idx_contracts_client_id (client_id),
  INDEX idx_contracts_partner_id (partner_id),
  INDEX idx_contracts_status (status),
  INDEX idx_contracts_start_date (start_date),
  INDEX idx_contracts_end_date (end_date),
  INDEX idx_contracts_created_at (created_at),
  INDEX idx_contracts_deleted_at (deleted_at),
  CONSTRAINT fk_contracts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_contracts_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_contracts_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
