CREATE TABLE IF NOT EXISTS notifications (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26),
  user_id CHAR(26) NOT NULL,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'system',
  category ENUM('info','success','warning','danger','reminder') NOT NULL DEFAULT 'info',
  severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'low',
  status ENUM('unread','read','archived','dismissed') NOT NULL DEFAULT 'unread',
  kind VARCHAR(100),
  entity_type VARCHAR(100),
  entity_id CHAR(26),
  read_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_notifications_company_id (company_id),
  INDEX idx_notifications_user_id (user_id),
  INDEX idx_notifications_status (status),
  INDEX idx_notifications_type (type),
  INDEX idx_notifications_severity (severity),
  INDEX idx_notifications_created_at (created_at),
  CONSTRAINT fk_notif_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
