CREATE TABLE IF NOT EXISTS alerts (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  type VARCHAR(100) NOT NULL,
  severity ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  title VARCHAR(255) NOT NULL,
  message TEXT,
  status ENUM('active','acknowledged','resolved','dismissed') NOT NULL DEFAULT 'active',
  entity_type VARCHAR(100),
  entity_id CHAR(26),
  rule_code VARCHAR(100),
  acknowledged_by CHAR(26),
  acknowledged_at TIMESTAMP NULL DEFAULT NULL,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alerts_company_id (company_id),
  INDEX idx_alerts_type (type),
  INDEX idx_alerts_severity (severity),
  INDEX idx_alerts_status (status),
  INDEX idx_alerts_entity (entity_type, entity_id),
  INDEX idx_alerts_created_at (created_at),
  CONSTRAINT fk_alerts_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_alerts_acknowledged_by FOREIGN KEY (acknowledged_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
