CREATE TABLE IF NOT EXISTS calendar_events (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  user_id CHAR(26),
  title VARCHAR(255) NOT NULL,
  description TEXT,
  event_type VARCHAR(100) NOT NULL,
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP NULL DEFAULT NULL,
  all_day BOOLEAN DEFAULT FALSE,
  status ENUM('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  entity_type VARCHAR(100),
  entity_id CHAR(26),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_cal_company_id (company_id),
  INDEX idx_cal_user_id (user_id),
  INDEX idx_cal_event_type (event_type),
  INDEX idx_cal_start_at (start_at),
  INDEX idx_cal_end_at (end_at),
  INDEX idx_cal_entity (entity_type, entity_id),
  INDEX idx_cal_created_at (created_at),
  CONSTRAINT fk_cal_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_cal_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
