CREATE TABLE IF NOT EXISTS financial_transactions (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  account_id CHAR(26) NOT NULL,
  transaction_type ENUM('income','expense','transfer','refund','adjustment') NOT NULL,
  category VARCHAR(100),
  reference VARCHAR(100),
  amount DECIMAL(15, 2) NOT NULL,
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  balance_after DECIMAL(15, 2),
  status ENUM('pending','completed','failed','cancelled','reversed') NOT NULL DEFAULT 'pending',
  description TEXT,
  entity_type VARCHAR(100),
  entity_id CHAR(26),
  transaction_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by CHAR(26),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ft_company_id (company_id),
  INDEX idx_ft_account_id (account_id),
  INDEX idx_ft_transaction_type (transaction_type),
  INDEX idx_ft_status (status),
  INDEX idx_ft_category (category),
  INDEX idx_ft_reference (reference),
  INDEX idx_ft_entity (entity_type, entity_id),
  INDEX idx_ft_transaction_date (transaction_date),
  INDEX idx_ft_created_at (created_at),
  CONSTRAINT fk_ft_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ft_account FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_ft_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
