CREATE TABLE IF NOT EXISTS invoices (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  client_id CHAR(26),
  partner_id CHAR(26),
  reference VARCHAR(100) NOT NULL,
  status ENUM('draft','issued','paid','partially_paid','overdue','cancelled','refunded') NOT NULL DEFAULT 'draft',
  subtotal DECIMAL(15, 2) NOT NULL DEFAULT 0,
  tax_rate DECIMAL(5, 4) NOT NULL DEFAULT 0.1800,
  tax_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  total DECIMAL(15, 2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(15, 2) NOT NULL DEFAULT 0,
  credit_applied DECIMAL(15, 2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  issued_at TIMESTAMP NULL DEFAULT NULL,
  due_at TIMESTAMP NULL DEFAULT NULL,
  paid_at TIMESTAMP NULL DEFAULT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  UNIQUE KEY uk_invoices_reference_company (company_id, reference),
  INDEX idx_invoices_company_id (company_id),
  INDEX idx_invoices_client_id (client_id),
  INDEX idx_invoices_partner_id (partner_id),
  INDEX idx_invoices_status (status),
  INDEX idx_invoices_issued_at (issued_at),
  INDEX idx_invoices_due_at (due_at),
  INDEX idx_invoices_created_at (created_at),
  INDEX idx_invoices_deleted_at (deleted_at),
  CONSTRAINT fk_invoices_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_invoices_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_invoices_partner FOREIGN KEY (partner_id) REFERENCES partners(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
