CREATE TABLE IF NOT EXISTS revenues (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  account_id CHAR(26),
  reference VARCHAR(100),
  revenue_type VARCHAR(100) NOT NULL,
  description TEXT,
  gross_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  commission DECIMAL(15, 2) NOT NULL DEFAULT 0,
  net_amount DECIMAL(15, 2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  status ENUM('pending','confirmed','cancelled') NOT NULL DEFAULT 'pending',
  period_start DATE,
  period_end DATE,
  entity_type VARCHAR(100),
  entity_id CHAR(26),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_revenues_company_id (company_id),
  INDEX idx_revenues_account_id (account_id),
  INDEX idx_revenues_revenue_type (revenue_type),
  INDEX idx_revenues_status (status),
  INDEX idx_revenues_period (period_start, period_end),
  INDEX idx_revenues_created_at (created_at),
  CONSTRAINT fk_revenues_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_revenues_account FOREIGN KEY (account_id) REFERENCES financial_accounts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
