CREATE TABLE IF NOT EXISTS subscription_plans (
  id CHAR(26) PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  code VARCHAR(50) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  description TEXT,
  price_monthly DECIMAL(15, 2) NOT NULL DEFAULT 0,
  price_yearly DECIMAL(15, 2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  max_vehicles INT DEFAULT 5,
  max_drivers INT DEFAULT 5,
  max_users INT DEFAULT 3,
  max_agencies INT DEFAULT 1,
  max_companies INT DEFAULT 1,
  max_documents INT DEFAULT 100,
  max_storage_gb INT DEFAULT 5,
  max_trips_per_month INT DEFAULT 50,
  max_fuel_records_per_month INT DEFAULT 50,
  max_maintenance_records_per_month INT DEFAULT 50,
  features JSON,
  is_active BOOLEAN DEFAULT TRUE,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sp_code (code),
  INDEX idx_sp_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
