CREATE TABLE IF NOT EXISTS subscriptions (
  id CHAR(26) PRIMARY KEY,
  company_id CHAR(26) NOT NULL,
  plan_id CHAR(26) NOT NULL,
  status ENUM('trialing','active','past_due','paused','cancelled','expired') NOT NULL DEFAULT 'trialing',
  billing_interval ENUM('monthly','yearly') NOT NULL DEFAULT 'monthly',
  price DECIMAL(15, 2) NOT NULL DEFAULT 0,
  currency VARCHAR(3) NOT NULL DEFAULT 'XAF',
  trial_start_date DATE,
  trial_end_date DATE,
  start_date DATE NOT NULL,
  end_date DATE,
  current_period_start DATE,
  current_period_end DATE,
  cancelled_at TIMESTAMP NULL DEFAULT NULL,
  cancellation_reason TEXT,
  renewal_date DATE,
  usage_data JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sub_company_id (company_id),
  INDEX idx_sub_plan_id (plan_id),
  INDEX idx_sub_status (status),
  INDEX idx_sub_current_period_end (current_period_end),
  INDEX idx_sub_renewal_date (renewal_date),
  CONSTRAINT fk_sub_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_sub_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
