/**
 * Navix Management — Points d'accès API (endpoints)
 * --------------------------------------------------------------------------
 * Source unique de vérité des chemins HTTP de chaque ressource. Les services
 * (`src/services/api`) référencent ces constantes — jamais d'URL codée en dur.
 * Les fonctions (ex. DETAIL) acceptent les paramètres d'identifiant.
 */

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  VEHICLES: {
    LIST: '/vehicles',
    DETAIL: (id) => `/vehicles/${id}`,
  },
  DRIVERS: {
    LIST: '/drivers',
    DETAIL: (id) => `/drivers/${id}`,
  },
  COMPANIES: {
    LIST: '/companies',
    DETAIL: (id) => `/companies/${id}`,
  },
  AGENCIES: {
    LIST: '/agencies',
    DETAIL: (id) => `/agencies/${id}`,
    STATS: '/agencies/stats',
    VEHICLES: (id) => `/agencies/${id}/vehicles`,
    DRIVERS: (id) => `/agencies/${id}/drivers`,
    ACTIVITY: (id) => `/agencies/${id}/activity`,
    ACTIVATE: (id) => `/agencies/${id}/activate`,
    DEACTIVATE: (id) => `/agencies/${id}/deactivate`,
  },
  ASSIGNMENTS: {
    LIST: '/assignments',
    DETAIL: (id) => `/assignments/${id}`,
    HISTORY: '/assignments/history',
  },
  TRIPS: {
    LIST: '/trips',
    DETAIL: (id) => `/trips/${id}`,
    HISTORY: '/trips/history',
  },
  FUEL: {
    LIST: '/fuel',
    DETAIL: (id) => `/fuel/${id}`,
    STATS: '/fuel/stats',
  },
  MAINTENANCE: {
    LIST: '/maintenance',
    DETAIL: (id) => `/maintenance/${id}`,
    STATS: '/maintenance/stats',
    CALENDAR: '/maintenance/calendar',
    HISTORY: '/maintenance/history',
  },
  DOCUMENTS: {
    LIST: '/documents',
    DETAIL: (id) => `/documents/${id}`,
    STATS: '/documents/stats',
    UPLOAD: '/documents/upload',
    PREVIEW: (id) => `/documents/${id}/preview`,
    DOWNLOAD: (id) => `/documents/${id}/download`,
    FILE_TYPES: '/documents/file-types',
    FILE_TYPE_DETAIL: (id) => `/documents/file-types/${id}`,
  },
  DASHBOARD: {
    OVERVIEW: '/dashboard/overview',
    FLEET: '/dashboard/fleet',
    FUEL: '/dashboard/fuel',
    MAINTENANCE: '/dashboard/maintenance',
    FINANCIAL: '/dashboard/financial',
    ALERTS: '/dashboard/alerts',
    ACTIVITIES: '/dashboard/activities',
    TOP_VEHICLES: '/dashboard/top-vehicles',
    TOP_DRIVERS: '/dashboard/top-drivers',
  },
  SUBSCRIPTIONS: {
    LIST: '/subscriptions',
    DETAIL: (id) => `/subscriptions/${id}`,
    CURRENT: '/subscriptions/current',
    FEATURES: '/subscriptions/features',
    PLAN_FEATURES: (planId) => `/subscriptions/plans/${planId}/features`,
    PLAN_LIMITS: (planId) => `/subscriptions/plans/${planId}/limits`,
    USAGE: (companyId) => `/subscriptions/usage/${companyId}`,
    CANCEL: (id) => `/subscriptions/${id}/cancel`,
    RESUME: (id) => `/subscriptions/${id}/resume`,
    RENEW: (id) => `/subscriptions/${id}/renew`,
    DELETE: (id) => `/subscriptions/${id}`,
  },
  INVOICES: {
    LIST: '/invoices',
    DETAIL: (id) => `/invoices/${id}`,
  },
  BILLING: {
    INVOICES: '/billing/invoices',
    INVOICE_DETAIL: (id) => `/billing/invoices/${id}`,
    INVOICE_ITEMS: (id) => `/billing/invoices/${id}/items`,
    INVOICE_ISSUE: (id) => `/billing/invoices/${id}/issue`,
    INVOICE_CANCEL: (id) => `/billing/invoices/${id}/cancel`,
    INVOICE_DOWNLOAD: (id) => `/billing/invoices/${id}/download`,
    PAYMENTS: '/billing/payments',
    PAYMENT_DETAIL: (id) => `/billing/payments/${id}`,
    PAYMENT_SIMULATE: '/billing/payments/simulate',
    PAYMENT_REFUND: (id) => `/billing/payments/${id}/refund`,
    CREDITS: '/billing/credits',
    DISCOUNTS: '/billing/discounts',
    HISTORY: '/billing/history',
    STATISTICS: '/billing/statistics',
    SETTINGS: '/billing/settings',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    UNREAD_COUNT: '/notifications/unread-count',
  },
  AUDIT: {
    LIST: '/audit-logs',
    DETAIL: (id) => `/audit-logs/${id}`,
    STATISTICS: '/audit-logs/statistics',
    EXPORT: '/audit-logs/export',
  },
  USERS: {
    LIST: '/users',
    DETAIL: (id) => `/users/${id}`,
    CREATE: '/users',
    UPDATE: (id) => `/users/${id}`,
    DELETE: (id) => `/users/${id}`,
    ACTIVATE: (id) => `/users/${id}/activate`,
    DEACTIVATE: (id) => `/users/${id}/deactivate`,
    SUSPEND: (id) => `/users/${id}/suspend`,
    REACTIVATE: (id) => `/users/${id}/reactivate`,
    INVITE: (id) => `/users/${id}/invite`,
    RESET_PASSWORD: (id) => `/users/${id}/reset-password`,
    STATISTICS: '/users/statistics',
  },
  ROLES: {
    LIST: '/roles',
    DETAIL: (id) => `/roles/${id}`,
    CREATE: '/roles',
    UPDATE: (id) => `/roles/${id}`,
    DELETE: (id) => `/roles/${id}`,
    ACTIVATE: (id) => `/roles/${id}/activate`,
    DEACTIVATE: (id) => `/roles/${id}/deactivate`,
    ASSIGN_PERMISSIONS: (id) => `/roles/${id}/permissions`,
  },
  PERMISSIONS: {
    LIST: '/permissions',
    DETAIL: (id) => `/permissions/${id}`,
    MODULES: '/permissions/modules',
    STATISTICS: '/permissions/statistics',
  },
  REPORTS: {
    LIST: '/reports',
    DETAIL: (id) => `/reports/${id}`,
    CATEGORIES: '/reports/categories',
    FLEET: '/reports/fleet',
    VEHICLES: '/reports/vehicles',
    DRIVERS: '/reports/drivers',
    ASSIGNMENTS: '/reports/assignments',
    TRIPS: '/reports/trips',
    FUEL: '/reports/fuel',
    MAINTENANCE: '/reports/maintenance',
    DOCUMENTS: '/reports/documents',
    FINANCIAL: '/reports/financial',
    SUBSCRIPTIONS: '/reports/subscriptions',
    AUDIT: '/reports/audit',
    COMPANIES: '/reports/companies',
    CUSTOM: '/reports/custom',
    SAVE: '/reports',
    UPDATE: (id) => `/reports/${id}`,
    DELETE: (id) => `/reports/${id}`,
    EXPORT: '/reports/export',
    STATISTICS: '/reports/statistics',
  },
  SETTINGS: {
    LIST: '/settings',
    GENERAL: '/settings/general',
    COMPANY: '/settings/company',
    FLEET: '/settings/fleet',
    MAINTENANCE: '/settings/maintenance',
    FUEL: '/settings/fuel',
    DOCUMENTS: '/settings/documents',
    NOTIFICATIONS: '/settings/notifications',
    USER: '/settings/user',
    APPEARANCE: '/settings/appearance',
    REGIONAL: '/settings/regional',
    BILLING: '/settings/billing',
    SAAS: '/settings/saas',
    SECURITY: '/settings/security',
    SYSTEM: '/settings/system',
    UPDATE: (section) => `/settings/${section}`,
    RESET: (section) => `/settings/${section}/reset`,
    RESET_ALL: '/settings/reset-all',
  },
};
