/**
 * Navix Settings — API publique de la feature.
 * Seuls les non-composants sont exportés ici ; les composants sont importés
 * via `@/features/settings/components`.
 */
export {
  useSettingsStore,
  getSettingsCompanyScopeId,
  getSettingsUserScopeId,
} from './store';
export {
  settingsService,
  getSettings,
  updateSettings,
  getSectionSettings,
  updateSectionSettings,
  resetSectionSettings,
  resetAllSettings,
  emitSettingsNotification,
  emitSettingsAuditLog,
} from './services';
export {
  useSettings,
  useSettingsSection,
  useGeneralSettings,
  useCompanySettings,
  useFleetSettings,
  useMaintenanceSettings,
  useFuelSettings,
  useDocumentSettings,
  useNotificationSettings,
  useUserSettings,
  useAppearanceSettings,
  useRegionalSettings,
  useBillingSettings,
  useSaasSettings,
  useSecuritySettings,
  useSystemSettings,
} from './hooks';
export {
  generalSettingsSchema,
  generalSettingsDefaultValues,
  companySettingsSchema,
  companySettingsDefaultValues,
  fleetSettingsSchema,
  fleetSettingsDefaultValues,
  maintenanceSettingsSchema,
  maintenanceSettingsDefaultValues,
  fuelSettingsSchema,
  fuelSettingsDefaultValues,
  documentSettingsSchema,
  documentSettingsDefaultValues,
  notificationSettingsSchema,
  notificationSettingsDefaultValues,
  userSettingsSchema,
  userSettingsDefaultValues,
  appearanceSettingsSchema,
  appearanceSettingsDefaultValues,
  regionalSettingsSchema,
  regionalSettingsDefaultValues,
  billingSettingsSchema,
  billingSettingsDefaultValues,
  saasSettingsSchema,
  saasSettingsDefaultValues,
  securitySettingsSchema,
  securitySettingsDefaultValues,
  systemSettingsSchema,
  systemSettingsDefaultValues,
  SETTINGS_SCHEMAS,
  SETTINGS_DEFAULT_VALUES,
  getSettingsFormValues,
  getSettingsPayload,
} from './schemas';
export {
  SETTINGS_SECTIONS,
  SETTINGS_SECTION_VALUES,
  SETTINGS_SECTION_GROUPS,
  getSettingsSection,
  SENSITIVE_SETTINGS_SECTIONS,
  LANGUAGES,
  COUNTRIES,
  TIMEZONES,
  DATE_FORMATS,
  TIME_FORMATS,
  FIRST_DAYS_OF_WEEK,
  NUMBER_LOCALES,
  DECIMAL_SEPARATORS,
  THOUSAND_SEPARATORS,
  DISTANCE_UNITS,
  CONSUMPTION_UNITS,
  FUEL_UNITS,
  EXPIRATION_ALERT_DAYS,
  DOCUMENT_MIME_TYPES,
  UI_DENSITIES,
  SIDEBAR_MODES,
  CURRENCIES,
  CURRENCY_VALUES,
  TAX_RATES,
  TAX_RATE_VALUES,
  DOCUMENT_TYPES,
  DOCUMENT_TYPE_VALUES,
} from './constants';
