/**
 * Navix Notifications — Constantes du module Notifications & Alertes
 */
export {
  NOTIFICATION_TYPES,
  NOTIFICATION_TYPE_VALUES,
  getNotificationType,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CATEGORY_VALUES,
  getNotificationCategory,
  NOTIFICATION_SEVERITIES,
  NOTIFICATION_SEVERITY_VALUES,
  getNotificationSeverity,
  SEVERITY_ORDER,
  NOTIFICATION_STATUSES,
  NOTIFICATION_STATUS_VALUES,
  getNotificationStatus,
  NOTIFICATION_KINDS,
  NOTIFICATION_KIND_VALUES,
  getNotificationKind,
  ALERT_RULES,
  ALERT_RULE_VALUES,
  getAlertRule,
  RESOURCE_TYPES,
  getResourcePath,
  NOTIFICATION_ICON,
  DEFAULT_PAGE_SIZE,
  PAGE_SIZE_OPTIONS,
  NOTIFICATION_SORT_OPTIONS,
  SORT_DIRECTIONS,
  formatNotificationDate,
  formatNotificationDateTime,
  formatNotificationRelative,
  countUrgentNotifications,
} from './notification.constants';
