export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

export const ERROR_CODES = {
  APP_ERROR: 'APP_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  PASSWORD_POLICY: 'PASSWORD_POLICY',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
};

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  COMPANY_OWNER: 'company_owner',
  COMPANY_ADMIN: 'company_admin',
  FLEET_MANAGER: 'fleet_manager',
  DISPATCHER: 'dispatcher',
  DRIVER: 'driver',
  MECHANIC: 'mechanic',
  ACCOUNTANT: 'accountant',
  VIEWER: 'viewer',
  CLIENT_ENTERPRISE: 'client_enterprise',
  CLIENT_INDIVIDUAL: 'client_individual',
  PARTNER: 'partner',
};

export const PUBLIC_REGISTRATION_ROLES = [
  ROLES.CLIENT_ENTERPRISE,
  ROLES.DRIVER,
  ROLES.PARTNER,
];

export const TENANT_SCOPED_ROLES = [
  ROLES.COMPANY_OWNER,
  ROLES.COMPANY_ADMIN,
  ROLES.FLEET_MANAGER,
  ROLES.DISPATCHER,
  ROLES.DRIVER,
  ROLES.MECHANIC,
  ROLES.ACCOUNTANT,
  ROLES.VIEWER,
  ROLES.CLIENT_ENTERPRISE,
  ROLES.CLIENT_INDIVIDUAL,
  ROLES.PARTNER,
];
