export {
  useSettings,
  useSettingsSection,
  useGeneralSettings,
  useCompanySettings,
  useFleetSettings,
  useMaintenanceSettings,
  useFuelSettings,
  useDocumentSettings,
  useNotificationSettings,
  useUserSettings,
  useAppearanceSettings,
  useRegionalSettings,
  useBillingSettings,
  useSaasSettings,
  useSecuritySettings,
  useSystemSettings,
} from './useSettings';
